### PR TITLE
Fix issue #21

### LINKED ISSUE #21: [BUG] Transaction fetching throws an error
## Summary
Transactions are not fetched correctly. Logs print the following error:
`Cannot destructure property 'hash' of 'transaction' as it is null.`

### PR DESCRIPTION
**Pull request by Abrom8**
Fixes #21 

## Proposed Changes

  - improve `getLatestTxBlockNumber` query
  - add checks to prevent halting of the sync
  - add additional logging

### CODE REVIEW

File: src/utils/fetchTransactions.ts [hunk 1]
```diff
@@ -9,8 +10,8 @@ const providerURL = process.env.PROVIDER_URL || 'https://rpc.gaiaxtestnet.oceanp
 const provider = new ethers.providers.JsonRpcProvider(providerURL)
 
 async function getLatestTxBlockNumber() {
-  const txArray = await Transaction.findOne({}).sort('-blockNumber').exec()
-  return txArray?.blockNumber
+  const txArray = await Transaction.find().sort({ blockNumber: -1 }).limit(1)
+  return txArray?.[0]?.blockNumber
```
Comment (oceanByte) [inline src/utils/fetchTransactions.ts:14]: question(blocking): What is the reason behind changing from `findOne` to `find`?

**Review by oceanByte — CHANGES_REQUESTED** [review]

File: src/utils/fetchTransactions.ts [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import { ethers } from 'ethers'
+import { Block as IBlock } from 'interfaces/block.interface'
 import { Transaction as TransactionI } from 'interfaces/transaction.interface'
```
Comment (moritzkirstein) [inline src/utils/fetchTransactions.ts]: suggestion(non-blocking): we should probably be consistent here with the naming. I would suggest to name interfaces as `I{MODEL_NAME}` -> should be done directly in the interface file

File: src/utils/fetchTransactions.ts (hunk 1 above)
Comment (Abrom8) [reply src/utils/fetchTransactions.ts:14]: I checked the queries for problems and found that this query is more performant.

**Review by oceanByte — APPROVED** [review]
